# Generated by Django 4.2.4 on 2023-09-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
