# Generated by Django 4.2.4 on 2023-09-01 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0002_cinema_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='movie',
        ),
    ]
