# Generated by Django 4.2.4 on 2023-09-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinemaApp', '0003_rename_title_movie_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='movie',
            field=models.ManyToManyField(to='CinemaApp.movie'),
        ),
    ]
